# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'Starwar_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Starwar_demo
  pod 'Alamofire'
end
